-- DROP DATABASE mentorama;

CREATE DATABASE mentorama;

CREATE TABLE pedidos(
	id INT PRIMARY KEY,
	produtos VARCHAR(50),
	desconto_aplicado DECIMAL, 
	valor_cobrado DECIMAL,
	cliente VARCHAR(50));

CREATE TABLE clientes(
	id INT PRIMARY KEY,
	nome VARCHAR(220),
	telefone VARCHAR(11));
	
ALTER TABLE pedidos
	ADD COLUMN id_cliente INT;
	
ALTER TABLE pedidos
	ADD CONSTRAINT fk_cliente
	FOREIGN KEY (id_cliente)
	REFERENCES clientes(id);


ALTER TABLE pedidos
	DROP COLUMN cliente;
	
	
CREATE TABLE produtos(
	id INT PRIMARY KEY,
	descricao VARCHAR(50),
	valor DECIMAL);

	
CREATE TABLE itens_pedidos(
	id_pedido INT,
	id_produto INT,
	quantidade INT,
	PRIMARY KEY(id_pedido, id_produto),
	CONSTRAINT fk_pedidos
		FOREIGN KEY (id_pedido)
		REFERENCES pedidos(id),
	CONSTRAINT fk_produtos
		FOREIGN KEY (id_produto)
			REFERENCES produtos(id)
		);

ALTER TABLE pedidos
	DROP COLUMN valor_cobrado;
	
INSERT INTO clientes (id, nome) VALUES
	(1, 'Vinicius')

SELECT * FROM clientes;

UPDATE clientes SET telefone = '819999-9999' 
	WHERE id = 1;

DELETE FROM clientes 
	WHERE id=1;

INSERT INTO clientes VALUES
	(2, 'Vinicius', '819999-9999'),
	(3, 'Vinicius', '819999-9999'),
	(4, 'Vinicius', '819999-9999');
	
DELETE FROM clientes;

ALTER TABLE clientes
	ALTER COLUMN id
		ADD GENERATED BY DEFAULT AS IDENTITY;
		
INSERT INTO clientes (nome, telefone) VALUES
	('Vinicius', '819999-9999'),
	('Vinicius', '819999-9999'),
	('Vinicius', '819999-9999');

SELECT p.id AS id_pedido, c.nome, c.telefone
	FROM pedidos p 
	INNER JOIN clientes c
	ON p.id_cliente = c.id
	INNER JOIN itens_pedidos ip
	ON p.id = id_pedidos
	INNER JOIN produtos p2
	ON ip.id_produto = p2.id
WHERE p2.descricao LIKE 'Coca Cola%'

SELECT * FROM produtos p

SELECT p.id AS id_pedido, c.nome, SUM(p2.valor * ip.quantidade) AS valor_total
	FROM pedidos p 
	INNER JOIN clientes c
	ON p.id_cliente = c.id
	INNER JOIN itens_pedidos ip
	ON p.id = id_pedidos
	INNER JOIN produtos p2
	ON ip.id_produto = p2.id
GROUP BY p.id, c.nome 
ORDER BY valor_total DESC
LIMIT 2;


SELECT max(id) FROM clientes c;

SELECT * FROM pedidos p2 WHERE p2.id_cliente
	in(
		SELECT id from clientes c WHERE id < 3
		);


CREATE TABLE funcionarios (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY  
);
	
	
	
	
	
	