CREATE DATABASE sistema_hospitalar;
-- DROP DATABASE sistema_hospitalar;

-- DROP TABLE historico_internacoes;
-- DROP TABLE funcionarios_saude;
-- DROP TABLE pacientes;

-- CRIAÇÃO DE TABELAS

CREATE TABLE funcionarios_saude (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    matricula INT NOT NULL, 
    nome VARCHAR(220) NOT NULL,
    departamento VARCHAR(100),
    cargo VARCHAR(100),
    telefone VARCHAR(11) NOT NULL
);

CREATE TABLE pacientes (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(220) NOT NULL,
    telefone VARCHAR(11) NOT NULL,
    data_nascimento DATE NOT NULL
);

CREATE TABLE historico_internacoes(
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    diagnostico TEXT NOT NULL,
    data_hora_entrada TIMESTAMP NOT NULL,
    data_hora_saida TIMESTAMP,
    id_paciente INT,
    id_funcionario INT,
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id),
    FOREIGN KEY (id_funcionario) REFERENCES funcionarios_saude(id)
);


-- INSERÇÃO DE DADOS


INSERT INTO funcionarios_saude (matricula, nome, departamento, cargo, telefone) VALUES
	(1259, 'Maria Joaquina', 'Enfermagem','Enfermeiro(a)', '85998768719'),
	(1256, 'Carlos Menezes', 'Enfermagem','Técnico(a) Enfermagem', '85999762719'),
	(1254, 'João Maurício', 'Pediatria','Médico(a)', '85998328712'),
	(1211, 'Carla Silva', 'Clinica Geral','Médico(a)', '85998740119'),
	(1273, 'Joana Azevedo', 'Enfermagem','Enfermeiro(a)', '85921940119');	
	
INSERT INTO pacientes (nome, telefone , data_nascimento) VALUES
	('Nayara Rocha', '85974466358', '15-08-2010'),
	('Cris Mota', '85997816439', '1986-12-25'),
	('Ronaldo Oliveira', '85997274339', '1992-06-25');

INSERT INTO historico_internacoes(diagnostico, data_hora_entrada , data_hora_saida , 
								  id_paciente, id_funcionario) VALUES
	('Catapora', '2022-02-22 19:10:25','2022-02-22 20:20:25', 1, 3 ),
	('Suspeita Covid', '2022-02-22 14:55:14','2022-02-22 15:40:10', 2, 2),
	('Sinusite', '2022-02-10 08:22:24',  '2022-02-10 09:10:32', 3, 5),
	('Infecção intestinal', '2022-02-22 13:30:59', null , 3, 3);


-- SELEÇÃO GERAL DE DADOS


SELECT * FROM funcionarios_saude;
SELECT * FROM pacientes;
SELECT * FROM historico_internacoes;

-- AGRUPAMENTOS 

SELECT h.id_paciente, p.nome, COUNT(h.id_paciente) AS quantidade_internacoes 
	FROM historico_internacoes h 
	INNER JOIN pacientes p
	ON h.id_paciente = p.id
GROUP BY h.id_paciente, p.id
ORDER BY quantidade_internacoes DESC;


SELECT departamento, COUNT(departamento) AS quantidade_funcionarios
	FROM funcionarios_saude 
GROUP BY departamento;